//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT4RPG.BU
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Character
    {
        public Character()
        {
            this.Uitrustingen = new HashSet<Uitrusting>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public int Levens { get; set; }
        public int Aanval { get; set; }
        public int Verdediging { get; set; }
    
        public virtual ICollection<Uitrusting> Uitrustingen { get; set; }
    }
}
